# fly.toml app configuration file generated for fill-damp-hill-4323 on 2023-12-18T05:22:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fill-damp-hill-4323"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
